apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: container-demo
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: container-demo.b3a7ca7e9aa5477faf6e.westeurope.aksapp.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: container-demo
                port:
                  number: 80